### ISSUE TITLE
Update is not done

### ISSUE THREAD

**Issue by theahadev** [slavanap/Windows10ManualUpdate#2] opened 2024-09-24 09:25 UTC
![image](https://github.com/user-attachments/assets/939a016a-e972-41a1-a7bf-70dbd46e2499)

i did everything as you described and disabled auto updates, when i update i get code 4 and it says updated, but it still stays there, even if i close and open the app again. And i don't think it really updated too.
Thanks.

**Comment by theahadev** [comment] 2024-09-24 09:27
I remembered that i forgot to to give you  some details:

Edition	Windows 10 IoT Enterprise LTSC
Version	21H2
Installed on	‎9/‎17/‎2024
OS build	19044.3324
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by slavanap** [comment] 2024-09-24 09:33
Try to reboot after update completion with this code, and try again. Maybe 2 or 3 times. Cumulative updates are split internally by Microsoft, but I think they handle it somehow with the modern UI. 
Otherwise, try to use system update interface to install updates (all pending updates will be installed)

**Comment by theahadev** [comment] 2024-09-24 10:14
> Try to reboot after update completion with this code, and try again. Maybe 2 or 3 times. Cumulative updates are split internally by Microsoft, but I think they handle it somehow with the modern UI. Otherwise, try to use system update interface to install updates (all pending updates will be installed)


I rebooted once, but i will try a few more times
I tried using Windows Update and Update Catalog but they didnt worked, it always gives the 0x800f081f error
Also, i wasn't waiting for an answer, that's why i answered late

**Comment by theahadev** [comment] 2024-09-24 10:38
its still there..

**Comment by theahadev** [comment] 2024-09-24 11:02
![image](https://github.com/user-attachments/assets/9c195970-ac85-407d-aa42-c287e8283430)
this also doesnt works :(

**Comment by slavanap** [comment] 2024-09-24 12:29
If Windows Update doesn’t report success, then the issue is with Windows. Basic approach is to run a repair with sfc /scannow
 and dism /online /cleanup-image /restorehealth
If it doesn’t help then report the issue to Microsoft Support.

**Comment by theahadev** [comment] 2024-09-24 12:52
Hmm, i already tried sfc and dism commands, i even reinstalled windows just to make sure
I will install another version then, thanks for the help 😉

**Closed as completed** 2024-09-29 15:01 UTC

**Comment by slavanap** [comment] 2024-09-29 15:02
Feel free to reopen in case errors associated with the software (not issues with the Windows OS itself) rise up.
